/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimalForm: typeof import('./src/components/AnimalForm.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AvatarCrooper: typeof import('./src/components/AvatarCrooper.vue')['default']
    BreedAnimal: typeof import('./src/components/BreedAnimal.vue')['default']
    BreedForm: typeof import('./src/components/BreedForm.vue')['default']
    ChatForm: typeof import('./src/components/ChatForm.vue')['default']
    FormPet: typeof import('./src/components/FormPet.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    MapMain: typeof import('./src/components/MapMain.vue')['default']
    MarkerMap: typeof import('./src/components/MarkerMap.vue')['default']
    MarkerTable: typeof import('./src/components/MarkerTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupportForm: typeof import('./src/components/SupportForm.vue')['default']
  }
}
