/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AvatarCrooper: typeof import('./src/components/AvatarCrooper.vue')['default']
    FormPet: typeof import('./src/components/FormPet.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MapMain: typeof import('./src/components/MapMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
